apiVersion: gossip.io/v1
kind: Simulation
metadata:
  name: high-mod-community-probabilities-complex-memory
spec:
  graphSelector:
    matchLabels:
      series: high-mod-series
  algorithm: community_probabilities_complex_memory
  visualize: false
  randomInitialization: false
  repetitions: 2
  priorPartnerFactor:
    - 0.25
    - 0.5
    - 0.75