FROM python:3.8-slim-buster

# install all requirements 
RUN pip install -U  --upgrade pip
COPY operator/requirements.txt /app/requirements.txt
RUN pip install -r /app/requirements.txt

# Copy the config to the container
COPY shared/cfg.py /app/cfg.py
# Copy the operator code to the container
COPY operator/simulation-operator.py /app/operator.py

# Run the operator
# https://kopf.readthedocs.io/en/stable/scopes/
CMD ["kopf", "run", "--all-namespaces", "--standalone", "/app/operator.py"]