apiVersion: gossip.io/v1
kind: Simulation
metadata:
  name: gnutella-series-weighted-factor
spec:
  graphSelector:
    matchLabels:
      series: gnutella-series
  algorithm: weighted_factor
  visualize: false
  randomInitialization: false
  repetitions: 10
  factor:
    - 1.25
    - 1.5
    - 1.75
    - 2
    - 2.25
    - 2.5
    - 2.75
    - 3