apiVersion: gossip.io/v1
kind: Simulation
metadata:
  name: gnutella-series-bn-wf-cm
spec:
  graphSelector:
    matchLabels:
      series: gnutella-series
  algorithm: betweenness_weighted_complex_memory
  visualize: false
  randomInitialization: false
  repetitions: 10
  factor:
    - 1.0
  weightingParamA:
    - 0
  priorPartnerFactor:
    - 0.1
    - 0.3
    - 0.5