# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import gossip_pb2 as gossip__pb2


class GossipStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Reset = channel.unary_unary(
                '/gossip.Gossip/Reset',
                request_serializer=gossip__pb2.ResetRequest.SerializeToString,
                response_deserializer=gossip__pb2.ResetResponse.FromString,
                )
        self.Gossip = channel.unary_unary(
                '/gossip.Gossip/Gossip',
                request_serializer=gossip__pb2.GossipRequest.SerializeToString,
                response_deserializer=gossip__pb2.GossipResponse.FromString,
                )
        self.History = channel.unary_unary(
                '/gossip.Gossip/History',
                request_serializer=gossip__pb2.HistoryRequest.SerializeToString,
                response_deserializer=gossip__pb2.HistoryResponse.FromString,
                )
        self.CurrentValue = channel.unary_unary(
                '/gossip.Gossip/CurrentValue',
                request_serializer=gossip__pb2.CurrentValueRequest.SerializeToString,
                response_deserializer=gossip__pb2.CurrentValueResponse.FromString,
                )
        self.StopApplication = channel.unary_unary(
                '/gossip.Gossip/StopApplication',
                request_serializer=gossip__pb2.StopApplicationRequest.SerializeToString,
                response_deserializer=gossip__pb2.StopApplicationResponse.FromString,
                )


class GossipServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Reset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Gossip(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def History(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CurrentValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopApplication(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GossipServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=gossip__pb2.ResetRequest.FromString,
                    response_serializer=gossip__pb2.ResetResponse.SerializeToString,
            ),
            'Gossip': grpc.unary_unary_rpc_method_handler(
                    servicer.Gossip,
                    request_deserializer=gossip__pb2.GossipRequest.FromString,
                    response_serializer=gossip__pb2.GossipResponse.SerializeToString,
            ),
            'History': grpc.unary_unary_rpc_method_handler(
                    servicer.History,
                    request_deserializer=gossip__pb2.HistoryRequest.FromString,
                    response_serializer=gossip__pb2.HistoryResponse.SerializeToString,
            ),
            'CurrentValue': grpc.unary_unary_rpc_method_handler(
                    servicer.CurrentValue,
                    request_deserializer=gossip__pb2.CurrentValueRequest.FromString,
                    response_serializer=gossip__pb2.CurrentValueResponse.SerializeToString,
            ),
            'StopApplication': grpc.unary_unary_rpc_method_handler(
                    servicer.StopApplication,
                    request_deserializer=gossip__pb2.StopApplicationRequest.FromString,
                    response_serializer=gossip__pb2.StopApplicationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gossip.Gossip', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Gossip(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gossip.Gossip/Reset',
            gossip__pb2.ResetRequest.SerializeToString,
            gossip__pb2.ResetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Gossip(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gossip.Gossip/Gossip',
            gossip__pb2.GossipRequest.SerializeToString,
            gossip__pb2.GossipResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def History(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gossip.Gossip/History',
            gossip__pb2.HistoryRequest.SerializeToString,
            gossip__pb2.HistoryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CurrentValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gossip.Gossip/CurrentValue',
            gossip__pb2.CurrentValueRequest.SerializeToString,
            gossip__pb2.CurrentValueResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StopApplication(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gossip.Gossip/StopApplication',
            gossip__pb2.StopApplicationRequest.SerializeToString,
            gossip__pb2.StopApplicationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
