# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gossip.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cgossip.proto\x12\x06gossip\"\x0f\n\rGossipRequest\"9\n\x0eGossipResponse\x12\'\n\x0bvalue_entry\x18\x01 \x01(\x0b\x32\x12.gossip.ValueEntry\"\x10\n\x0eHistoryRequest\"<\n\x0fHistoryResponse\x12)\n\rvalue_history\x18\x01 \x03(\x0b\x32\x12.gossip.ValueEntry\"5\n\nValueEntry\x12\x18\n\x10num_gossip_calls\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05\x32\x81\x01\n\x06Gossip\x12\x39\n\x06Gossip\x12\x15.gossip.GossipRequest\x1a\x16.gossip.GossipResponse\"\x00\x12<\n\x07History\x12\x16.gossip.HistoryRequest\x1a\x17.gossip.HistoryResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gossip_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GOSSIPREQUEST._serialized_start=24
  _GOSSIPREQUEST._serialized_end=39
  _GOSSIPRESPONSE._serialized_start=41
  _GOSSIPRESPONSE._serialized_end=98
  _HISTORYREQUEST._serialized_start=100
  _HISTORYREQUEST._serialized_end=116
  _HISTORYRESPONSE._serialized_start=118
  _HISTORYRESPONSE._serialized_end=178
  _VALUEENTRY._serialized_start=180
  _VALUEENTRY._serialized_end=233
  _GOSSIP._serialized_start=236
  _GOSSIP._serialized_end=365
# @@protoc_insertion_point(module_scope)
