apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: graphs.gossip.io
spec:
  group: gossip.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                adjacencyList:
                  type: string
                graphType:
                  type: string
                  default: 'undefined'
                modularity: 
                  type: string # refactor
                valueList:
                  type: string
                graphProperties:
                  additionalProperties:
                    type: string
                  type: object
              required: ['adjacencyList']
  scope: Namespaced
  names:
    plural: graphs
    singular: graph
    kind: Graph
    shortNames:
    - g