apiVersion: gossip.io/v1
kind: Graph
metadata:
  labels:
    series: test-series
  name: barab-n20-e1.3333
spec:
  adjacencyList:
  - "0 1 2 3 6 10 14,"
  - "1 16,"
  - "2 5 7,"
  - "3 4 5 6 13,"
  - "4,"
  - "5 8 9 17 19,"
  - "6,"
  - "7 9,"
  - "8,"
  - "9 11,"
  - "10 12,"
  - "11,"
  - "12 15,"
  - "13,"
  - "14 18,"
  - "15,"
  - "16,"
  - "17,"
  - "18,"
  - "19,"
  graphProperties:
    assortativity: "-0.281"
    averageAuthorityScore: "0.05"
    averageBetweennessCentrality: "0.1158"
    averageClosenessCentrality: "0.339"
    averageCommunitySize: "9.5"
    averageDegreeCentrality: "0.1158"
    averageEccentricity: "5.35"
    averageEdgeDegree: "2.2"
    averageEigenvectorCentrality: "0.1817"
    averageHubScore: "0.05"
    averageNearestNeighborsDegree: "3.6933"
    averagePageRank: "0.05"
    averagePathLength: "3.0842"
    averageRichClubCoefficient: "0.3642"
    clusterCoefficient: "0.0583"
    density: "0.1158"
    diameter: "7"
    edgeConnectivity: "1"
    modularity: "0.4669"
    newEdges: "1.3333"
    nodeConnectivity: "1"
    nodeCount: "20"
    numCommunities: "5"
    numEdges: "22"
    overallAverageCommunityClustering: "0.0583"
    overallStdevCommunityClustering: "0.2232"
    stdevAuthorityScore: "0.0368"
    stdevBetweennessCentrality: "0.1731"
    stdevClosenessCentrality: "0.0746"
    stdevCommunitySize: "1.2927"
    stdevDegreeCentrality: "0.0864"
    stdevEccentricity: "0.9333"
    stdevEdgeDegree: "5.9161"
    stdevEigenvectorCentrality: "0.1337"
    stdevHubScore: "0.0368"
    stdevNearestNeighborsDegree: "1.4825"
    stdevPageRank: "0.0318"
    stdevRichClubCoefficient: "0.2871"
    transitivity: "0.0577"
  graphType: "barabasi-albert"
  valueList: "51,14,98,3,78,91,63,32,6,77,85,49,24,9,46,58,67,11,36,95"
