apiVersion: gossip.io/v1
kind: Graph
metadata:
  labels:
    series: test-series
  name: barab-n20-e2.0
spec:
  adjacencyList:
  - "0 1 2 3 6 7 8 12,"
  - "1 3 13,"
  - "2 4 5 9,"
  - "3 4 6 7 9 10 11,"
  - "4 5 8 10 12 14 18,"
  - "5 19,"
  - "6,"
  - "7 16,"
  - "8,"
  - "9,"
  - "10 11 13 15,"
  - "11 14 16 18 19,"
  - "12 17,"
  - "13 15 17,"
  - "14,"
  - "15,"
  - "16,"
  - "17,"
  - "18,"
  - "19,"
  graphProperties:
    assortativity: "-0.3231"
    averageAuthorityScore: "0.05"
    averageBetweennessCentrality: "0.0655"
    averageClosenessCentrality: "0.4682"
    averageCommunitySize: "9.5"
    averageDegreeCentrality: "0.1895"
    averageEccentricity: "3.15"
    averageEdgeDegree: "3.6"
    averageEigenvectorCentrality: "0.2003"
    averageHubScore: "0.05"
    averageNearestNeighborsDegree: "5.1565"
    averagePageRank: "0.05"
    averagePathLength: "2.1789"
    averageRichClubCoefficient: "0.4877"
    clusterCoefficient: "0.2046"
    density: "0.1895"
    diameter: "4"
    edgeConnectivity: "2"
    modularity: "0.3144"
    newEdges: "2.0"
    nodeConnectivity: "2"
    nodeCount: "20"
    numCommunities: "3"
    numEdges: "36"
    overallAverageCommunityClustering: "0.2046"
    overallStdevCommunityClustering: "0.2994"
    stdevAuthorityScore: "0.0254"
    stdevBetweennessCentrality: "0.0843"
    stdevClosenessCentrality: "0.0712"
    stdevCommunitySize: "0.8127"
    stdevDegreeCentrality: "0.1099"
    stdevEccentricity: "0.4894"
    stdevEdgeDegree: "5.9161"
    stdevEigenvectorCentrality: "0.1019"
    stdevHubScore: "0.0254"
    stdevNearestNeighborsDegree: "1.4064"
    stdevPageRank: "0.0253"
    stdevRichClubCoefficient: "0.2711"
    transitivity: "0.1556"
  graphType: "barabasi-albert"
  valueList: "51,14,98,3,78,91,63,32,6,77,85,49,24,9,46,58,67,11,36,95"
