apiVersion: gossip.io/v1
kind: Simulation
metadata:
  name: simulation-test-series-weighted-complex-memory
spec:
  graphSelector:
    matchLabels:
      series: test-series
  algorithm: weighted_factor_complex_memory
  visualize: true
  randomInitialization: false
  repetitions: 2
  factor:
    - 1.25
    - 1.5
  priorPartnerFactor:
    - 0.5
    - 0.75
  simulationProperties:
    test: "42"
    anotherTest: "123"