apiVersion: gossip.io/v1
kind: Simulation
metadata:
  name: my-simulation-weighted-complex-memory
spec:
  graphSelector:
    matchLabels:
      name: barab-n20-e1.0
  algorithm: weighted_factor_complex_memory
  repetitions: 4
  visualize: true
  randomInitialization: false
  factor:
    - 1.25
  priorPartnerFactor:
    - 0.75
  simulationProperties:
    test: "42"
    anotherTest: "123"