apiVersion: v1
kind: Pod
metadata:
  name: test-node-1
  labels:
    app: gossip
    graph: test
    node: node-1
spec:
  restartPolicy: OnFailure
  containers:
  - name: node-example
    image: xwoodpecker/node-example:latest
    env:
    - name: NEIGHBORS
      value: test-node-2,test-node-3,
    ports:
      - containerPort: 90
        name: tcp
      - containerPort: 50051
        name: grpc
---
apiVersion: v1
kind: Pod
metadata:
  name: test-node-2
  labels:
    app: gossip
    graph: test
    node: node-2
spec:
  restartPolicy: OnFailure
  containers:
  - name: node-example
    image: xwoodpecker/node-example:latest
    env:
    - name: NEIGHBORS
      value: test-node-1,test-node-3,
    ports:
      - containerPort: 90
        name: tcp
      - containerPort: 50051
        name: grpc
---
apiVersion: v1
kind: Pod
metadata:
  name: test-node-3
  labels:
    app: gossip
    graph: test
    node: node-3
spec:
  restartPolicy: OnFailure
  containers:
  - name: node-example
    image: xwoodpecker/node-example:latest
    env:
    - name: NEIGHBORS
      value: test-node-1,test-node-2,test-node-4,
    ports:
      - containerPort: 90
        name: tcp
      - containerPort: 50051
        name: grpc
---
apiVersion: v1
kind: Pod
metadata:
  name: test-node-4
  labels:
    app: gossip
    graph: test
    node: node-4
spec:
  restartPolicy: OnFailure
  containers:
  - name: node-example
    image: xwoodpecker/node-example:latest
    env:
    - name: NEIGHBORS
      value: test-node-3,test-node-5,
    ports:
      - containerPort: 90
        name: tcp
      - containerPort: 50051
        name: grpc

---

apiVersion: v1
kind: Pod
metadata:
  name: test-node-5
  labels:
    app: gossip
    graph: test
    node: node-5
spec:
  restartPolicy: OnFailure
  containers:
  - name: node-example
    image: xwoodpecker/node-example:latest
    env:
    - name: NEIGHBORS
      value: test-node-4,test-node-6,test-node-7,
    ports:
      - containerPort: 90
        name: tcp
      - containerPort: 50051
        name: grpc

---

apiVersion: v1
kind: Pod
metadata:
  name: test-node-6
  labels:
    app: gossip
    graph: test
    node: node-6
spec:
  restartPolicy: OnFailure
  containers:
  - name: node-example
    image: xwoodpecker/node-example:latest
    env:
    - name: NEIGHBORS
      value: test-node-5,test-node-7,
    ports:
      - containerPort: 90
        name: tcp
      - containerPort: 50051
        name: grpc

---

apiVersion: v1
kind: Pod
metadata:
  name: test-node-7
  labels:
    app: gossip
    graph: test
    node: node-7
spec:
  restartPolicy: OnFailure
  containers:
  - name: node-example
    image: xwoodpecker/node-example:latest
    env:
    - name: NEIGHBORS
      value: test-node-6,test-node-8,
    ports:
      - containerPort: 90
        name: tcp
      - containerPort: 50051
        name: grpc

---

apiVersion: v1
kind: Pod
metadata:
  name: test-node-8
  labels:
    app: gossip
    graph: test
    node: node-8
spec:
  restartPolicy: OnFailure
  containers:
  - name: node-example
    image: xwoodpecker/node-example:latest
    env:
    - name: NEIGHBORS
      value: test-node-7,
    ports:
      - containerPort: 90
        name: tcp
      - containerPort: 50051
        name: grpc