apiVersion: v1
kind: Pod
metadata:
  name: test-node-1
  labels:
    app: gossip
    graph: test
    node: node-1
spec:
  containers:
  - name: node-example
    image: xwoodpecker/node-example:latest
    env:
    - name: NEIGHBORS
      value: test-node-2,test-node-3,
    ports:
      - containerPort: 90
        name: tcp
      - containerPort: 50051
        name: grpc
---
apiVersion: v1
kind: Pod
metadata:
  name: test-node-2
  labels:
    app: gossip
    graph: test
    node: node-2
spec:
  containers:
  - name: node-example
    image: xwoodpecker/node-example:latest
    env:
    - name: NEIGHBORS
      value: test-node-1,test-node-3,
    ports:
      - containerPort: 90
        name: tcp
      - containerPort: 50051
        name: grpc
---
apiVersion: v1
kind: Pod
metadata:
  name: test-node-3
  labels:
    app: gossip
    graph: test
    node: node-3
spec:
  containers:
  - name: node-example
    image: xwoodpecker/node-example:latest
    env:
    - name: NEIGHBORS
      value: test-node-1,test-node-2,
    ports:
      - containerPort: 90
        name: tcp
      - containerPort: 50051
        name: grpc