apiVersion: v1
kind: Pod
metadata:
  name: node-1
  labels:
    app: node
spec:
  containers:
  - name: node-example
    image: xwoodpecker/node-example:latest
    command: ["python", "my_script.py"]
    env:
    - name: NODE_2_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP