apiVersion: v1
kind: Pod
metadata:
  name: test-runner
  labels:
    app: gossip
    graph: test
    node: runner
spec:
  containers:
  - name: runner-example
    image: xwoodpecker/runner-example:latest
    env:
    - name: NODES
      value: test-node-1,test-node-2,test-node-3,
    ports:
      - containerPort: 50051
        name: grpc