apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-configmap
data:
  MINIO_ENDPOINT: "minio-custom:9000"
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secrets
type: Opaque
data:
  MINIO_USER: YWRtaW4=
  MINIO_PASSWORD: UzRQZWs3Qjhnbg==