apiVersion: gossip.io/v1
kind: Simulation
metadata:
  name: high-mod-ev-wf
spec:
  graphSelector:
    matchLabels:
      series: high-mod-series
  algorithm: eigenvector_weighted
  visualize: false
  randomInitialization: false
  repetitions: 1
  factor:
    - 1.0
  weightingParamA:
    - 0