apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-operator
  template:
    metadata:
      labels:
        app: simple-operator
    spec:
      serviceAccountName: simple-operator-sa
      containers:
        - name: simple-operator
          image: xwoodpecker/simple-operator:latest 