apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: simulations.gossip.io
spec:
  group: gossip.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                graphSelector:
                  type: object
                  properties:
                    matchLabels:
                      type: object
                      additionalProperties:
                        type: string
                algorithm:
                  type: string
  scope: Namespaced
  names:
    plural: simulations
    singular: simulation
    kind: Simulation
    shortNames:
    - sim